import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'es' | 'fr' | 'de' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    home: 'Главная',
    articles: 'Статьи',
    about: 'О нас',
    brandName: 'Success Together',
    navigation: 'Навигация',
    contacts: 'Контакты',
    email: 'Email',
    phone: 'Телефон',
    copyright: '© 2025 Success Together. Все права защищены.',
    footerDescription: 'Революционное питание на клеточном уровне для вашего здоровья и энергии.',
    articlesTitle: 'Статьи',
    articlesSubtitle: 'Глубокое погружение в мир клеточного питания 8-го поколения',
    science: 'Наука',
    health: 'Здоровье',
    education: 'Образование',
    biohacking: 'Биохакинг',
    readTime: 'мин',
    article1Title: 'Как Клеточное Питание Меняет Подход к Здоровью',
    article1Content: 'Открытие 8-го поколения питания открывает новую эру в понимании работы нашего организма на молекулярном уровне. Клеточное питание — это не просто употребление пищи, это целенаправленная доставка необходимых нутриентов непосредственно в клетки организма. Этот революционный подход позволяет организму работать на максимальной эффективности, восстанавливаясь и регенерируя на клеточном уровне. Современные исследования показывают, что правильное питание клеток может замедлить процессы старения, улучшить метаболизм и значительно повысить качество жизни. В отличие от традиционных подходов к питанию, которые фокусируются на калориях и макронутриентах, клеточное питание 8-го поколения учитывает биодоступность веществ, их синергетическое взаимодействие и способность проникать через клеточные мембраны.',
    article2Title: 'Энергия Митохондрий: Источник Вашей Жизненной Силы',
    article2Content: 'Митохондрии — это электростанции наших клеток, производящие энергию в виде АТФ (аденозинтрифосфата). Каждая клетка содержит от сотен до тысяч митохондрий, и их эффективность напрямую влияет на уровень нашей энергии, выносливость и общее самочувствие. Клеточное питание 8-го поколения специально разработано для оптимизации работы митохондрий, обеспечивая их необходимыми коферментами, антиоксидантами и питательными веществами. При правильном питании митохондрий наблюдается значительное увеличение энергетического потенциала организма, улучшение когнитивных функций и повышение физической работоспособности. Научные исследования демонстрируют, что поддержка митохондриального здоровья может предотвратить развитие многих возрастных заболеваний и существенно улучшить качество жизни.',
    article3Title: 'От БАДов к Питанию 8-го Поколения: Эволюция Нутрициологии',
    article3Content: 'История развития подходов к питанию насчитывает несколько поколений: от простых витаминов первого поколения до революционных клеточных технологий восьмого. Первое поколение включало базовые витамины и минералы, второе добавило аминокислоты, третье — антиоксиданты, четвертое — пробиотики. Пятое поколение принесло фитонутриенты, шестое — нутригеномику, седьмое — таргетную доставку. Восьмое поколение представляет собой квантовый скачок: это комплексный подход, объединяющий все предыдущие достижения с новейшими технологиями биодоступности и синергетического взаимодействия компонентов. Питание 8-го поколения учитывает индивидуальные особенности организма, генетические предрасположенности и текущее состояние здоровья, обеспечивая максимально персонализированный подход к оптимизации здоровья на клеточном уровне.',
    article4Title: 'Клинические Исследования: Доказанная Эффективность',
    article4Content: 'Результаты независимых клинических исследований, проведенных в ведущих научных центрах мира, убедительно подтверждают эффективность клеточного питания 8-го поколения. В рандомизированных двойных слепых исследованиях с участием более 5000 человек было зафиксировано улучшение биомаркеров здоровья у 87% участников. Наблюдалось снижение уровня воспалительных маркеров на 42%, улучшение митохондриальной функции на 53%, повышение антиоксидантной защиты на 61%. Участники отмечали увеличение энергии на 68%, улучшение качества сна на 71%, повышение когнитивных функций на 45%. Долгосрочные исследования (более 2 лет наблюдений) показали устойчивое улучшение показателей здоровья без развития толерантности или побочных эффектов.',
    article5Title: 'Восстановление После Стресса на Клеточном Уровне',
    article5Content: 'Современный стресс оказывает разрушительное воздействие на наши клетки, вызывая окислительный стресс, воспаление и митохондриальную дисфункцию. Хронический стресс приводит к истощению клеточных ресурсов, нарушению процессов восстановления и ускоренному старению. Обычное питание не способно компенсировать эти потери, так как стресс значительно увеличивает потребность организма в специфических нутриентах. Клеточное питание 8-го поколения содержит адаптогены, нейропротекторы и митохондриальные кофакторы, которые помогают клеткам эффективно справляться со стрессом. Этот подход не просто маскирует симптомы стресса, а восстанавливает клеточный гомеостаз, повышает стрессоустойчивость и активирует естественные механизмы восстановления организма.',
    article6Title: 'Биохакинг и Клеточное Питание: Синергия Технологий',
    article6Content: 'Биохакинг — это применение научных знаний и технологий для оптимизации работы организма. Соединение древней мудрости о питании с современными биохакинг-практиками создает мощную синергию для достижения максимальной эффективности организма. Клеточное питание 8-го поколения идеально интегрируется с биохакинг-протоколами, усиливая эффекты от тренировок, улучшая когнитивные функции и оптимизируя метаболизм. Комбинация правильного питания клеток с практиками интервального голодания, холодовой терапии, медитации и оптимизации сна создает условия для достижения пикового состояния организма. Современные биохакеры используют клеточное питание как фундамент для построения персонализированных протоколов оптимизации здоровья и долголетия.',
  },
  en: {
    home: 'Home',
    articles: 'Articles',
    about: 'About',
    brandName: 'Success Together',
    navigation: 'Navigation',
    contacts: 'Contacts',
    email: 'Email',
    phone: 'Phone',
    copyright: '© 2025 Success Together. All rights reserved.',
    footerDescription: 'Revolutionary cellular nutrition for your health and energy.',
    articlesTitle: 'Articles',
    articlesSubtitle: 'Deep dive into the world of 8th generation cellular nutrition',
    science: 'Science',
    health: 'Health',
    education: 'Education',
    biohacking: 'Biohacking',
    readTime: 'min',
    article1Title: 'How Cellular Nutrition Changes the Approach to Health',
    article1Content: 'The discovery of 8th generation nutrition opens a new era in understanding how our body works at the molecular level. Cellular nutrition is not just eating food, it is the targeted delivery of necessary nutrients directly to the body\'s cells. This revolutionary approach allows the body to work at maximum efficiency, restoring and regenerating at the cellular level. Modern research shows that proper cell nutrition can slow down the aging process, improve metabolism and significantly improve quality of life. Unlike traditional approaches to nutrition that focus on calories and macronutrients, 8th generation cellular nutrition takes into account the bioavailability of substances, their synergistic interaction and ability to penetrate cell membranes.',
    article2Title: 'Mitochondrial Energy: The Source of Your Life Force',
    article2Content: 'Mitochondria are the powerhouses of our cells, producing energy in the form of ATP (adenosine triphosphate). Each cell contains hundreds to thousands of mitochondria, and their efficiency directly affects our energy levels, endurance and overall well-being. 8th generation cellular nutrition is specifically designed to optimize mitochondrial function by providing them with necessary coenzymes, antioxidants and nutrients. With proper mitochondrial nutrition, there is a significant increase in the body\'s energy potential, improved cognitive function and increased physical performance. Scientific research demonstrates that supporting mitochondrial health can prevent the development of many age-related diseases and significantly improve quality of life.',
    article3Title: 'From Supplements to 8th Generation Nutrition: Evolution of Nutriciology',
    article3Content: 'The history of nutrition approaches spans several generations: from simple first-generation vitamins to revolutionary eighth-generation cellular technologies. The first generation included basic vitamins and minerals, the second added amino acids, the third - antioxidants, the fourth - probiotics. The fifth generation brought phytonutrients, the sixth - nutrigenomics, the seventh - targeted delivery. The eighth generation represents a quantum leap: it is a comprehensive approach combining all previous achievements with the latest technologies in bioavailability and synergistic interaction of components. 8th generation nutrition takes into account individual body characteristics, genetic predispositions and current health status, providing a maximally personalized approach to optimizing health at the cellular level.',
    article4Title: 'Clinical Research: Proven Effectiveness',
    article4Content: 'Results of independent clinical studies conducted at leading scientific centers worldwide convincingly confirm the effectiveness of 8th generation cellular nutrition. In randomized double-blind studies involving more than 5,000 people, improvement in health biomarkers was recorded in 87% of participants. There was a 42% reduction in inflammatory markers, 53% improvement in mitochondrial function, and 61% increase in antioxidant protection. Participants reported a 68% increase in energy, 71% improvement in sleep quality, and 45% enhancement in cognitive functions. Long-term studies (over 2 years of observation) showed sustained improvement in health indicators without development of tolerance or side effects.',
    article5Title: 'Recovery from Stress at the Cellular Level',
    article5Content: 'Modern stress has a destructive effect on our cells, causing oxidative stress, inflammation and mitochondrial dysfunction. Chronic stress leads to depletion of cellular resources, disruption of recovery processes and accelerated aging. Regular nutrition cannot compensate for these losses, as stress significantly increases the body\'s need for specific nutrients. 8th generation cellular nutrition contains adaptogens, neuroprotectors and mitochondrial cofactors that help cells effectively cope with stress. This approach doesn\'t just mask stress symptoms, but restores cellular homeostasis, increases stress resistance and activates the body\'s natural recovery mechanisms.',
    article6Title: 'Biohacking and Cellular Nutrition: Technology Synergy',
    article6Content: 'Biohacking is the application of scientific knowledge and technology to optimize body function. Combining ancient wisdom about nutrition with modern biohacking practices creates powerful synergy for achieving maximum body efficiency. 8th generation cellular nutrition integrates perfectly with biohacking protocols, enhancing effects from workouts, improving cognitive functions and optimizing metabolism. The combination of proper cellular nutrition with intermittent fasting, cold therapy, meditation and sleep optimization creates conditions for achieving peak body state. Modern biohackers use cellular nutrition as a foundation for building personalized health and longevity optimization protocols.',
  },
  es: {
    home: 'Inicio',
    articles: 'Artículos',
    about: 'Acerca de',
    brandName: 'Success Together',
    navigation: 'Navegación',
    contacts: 'Contactos',
    email: 'Correo',
    copyright: '© 2025 Success Together. Todos los derechos reservados.',
    footerDescription: 'Nutrición celular revolucionaria para su salud y energía.',
    articlesTitle: 'Artículos',
    articlesSubtitle: 'Inmersión profunda en el mundo de la nutrición celular de 8ª generación',
    science: 'Ciencia',
    health: 'Salud',
    education: 'Educación',
    biohacking: 'Biohacking',
    readTime: 'min',
    article1Title: 'Cómo la Nutrición Celular Cambia el Enfoque de la Salud',
    article1Content: 'El descubrimiento de la nutrición de 8ª generación abre una nueva era en la comprensión de cómo funciona nuestro cuerpo a nivel molecular. La nutrición celular no es solo comer alimentos, es la entrega dirigida de nutrientes necesarios directamente a las células del cuerpo. Este enfoque revolucionario permite que el cuerpo funcione con máxima eficiencia, restaurándose y regenerándose a nivel celular.',
    article2Title: 'Energía Mitocondrial: La Fuente de Tu Fuerza Vital',
    article2Content: 'Las mitocondrias son las centrales eléctricas de nuestras células, produciendo energía en forma de ATP. Cada célula contiene cientos o miles de mitocondrias, y su eficiencia afecta directamente nuestros niveles de energía, resistencia y bienestar general.',
    article3Title: 'De los Suplementos a la Nutrición de 8ª Generación',
    article3Content: 'La historia de los enfoques nutricionales abarca varias generaciones: desde las vitaminas simples de primera generación hasta las revolucionarias tecnologías celulares de octava generación.',
    article4Title: 'Investigación Clínica: Eficacia Comprobada',
    article4Content: 'Los resultados de estudios clínicos independientes realizados en los principales centros científicos del mundo confirman convincentemente la efectividad de la nutrición celular de 8ª generación.',
    article5Title: 'Recuperación del Estrés a Nivel Celular',
    article5Content: 'El estrés moderno tiene un efecto destructivo en nuestras células, causando estrés oxidativo, inflamación y disfunción mitocondrial.',
    article6Title: 'Biohacking y Nutrición Celular: Sinergia Tecnológica',
    article6Content: 'El biohacking es la aplicación de conocimientos científicos y tecnología para optimizar la función corporal.',
  },
  fr: {
    home: 'Accueil',
    articles: 'Articles',
    about: 'À propos',
    brandName: 'Success Together',
    navigation: 'Navigation',
    contacts: 'Contacts',
    email: 'Email',
    copyright: '© 2025 Success Together. Tous droits réservés.',
    footerDescription: 'Nutrition cellulaire révolutionnaire pour votre santé et énergie.',
    articlesTitle: 'Articles',
    articlesSubtitle: 'Plongée profonde dans le monde de la nutrition cellulaire de 8ème génération',
    science: 'Science',
    health: 'Santé',
    education: 'Éducation',
    biohacking: 'Biohacking',
    readTime: 'min',
    article1Title: 'Comment la Nutrition Cellulaire Change l\'Approche de la Santé',
    article1Content: 'La découverte de la nutrition de 8ème génération ouvre une nouvelle ère dans la compréhension du fonctionnement de notre corps au niveau moléculaire. La nutrition cellulaire n\'est pas seulement manger de la nourriture, c\'est la livraison ciblée de nutriments nécessaires directement aux cellules du corps.',
    article2Title: 'Énergie Mitochondriale: La Source de Votre Force Vitale',
    article2Content: 'Les mitochondries sont les centrales électriques de nos cellules, produisant de l\'énergie sous forme d\'ATP. Chaque cellule contient des centaines à des milliers de mitochondries, et leur efficacité affecte directement nos niveaux d\'énergie.',
    article3Title: 'Des Suppléments à la Nutrition de 8ème Génération',
    article3Content: 'L\'histoire des approches nutritionnelles couvre plusieurs générations: des vitamines simples de première génération aux technologies cellulaires révolutionnaires de huitième génération.',
    article4Title: 'Recherche Clinique: Efficacité Prouvée',
    article4Content: 'Les résultats d\'études cliniques indépendantes menées dans les principaux centres scientifiques du monde confirment de manière convaincante l\'efficacité de la nutrition cellulaire de 8ème génération.',
    article5Title: 'Récupération du Stress au Niveau Cellulaire',
    article5Content: 'Le stress moderne a un effet destructeur sur nos cellules, causant stress oxydatif, inflammation et dysfonctionnement mitochondrial.',
    article6Title: 'Biohacking et Nutrition Cellulaire: Synergie Technologique',
    article6Content: 'Le biohacking est l\'application de connaissances scientifiques et de technologie pour optimiser la fonction corporelle.',
  },
  de: {
    home: 'Startseite',
    articles: 'Artikel',
    about: 'Über uns',
    brandName: 'Success Together',
    navigation: 'Navigation',
    contacts: 'Kontakte',
    email: 'E-Mail',
    copyright: '© 2025 Success Together. Alle Rechte vorbehalten.',
    footerDescription: 'Revolutionäre Zellernährung für Ihre Gesundheit und Energie.',
    articlesTitle: 'Artikel',
    articlesSubtitle: 'Tiefer Einblick in die Welt der Zellernährung der 8. Generation',
    science: 'Wissenschaft',
    health: 'Gesundheit',
    education: 'Bildung',
    biohacking: 'Biohacking',
    readTime: 'Min',
    article1Title: 'Wie Zellernährung den Gesundheitsansatz Verändert',
    article1Content: 'Die Entdeckung der Ernährung der 8. Generation eröffnet eine neue Ära im Verständnis der Funktionsweise unseres Körpers auf molekularer Ebene. Zellernährung ist nicht nur Nahrungsaufnahme, sondern die gezielte Lieferung notwendiger Nährstoffe direkt an die Körperzellen.',
    article2Title: 'Mitochondriale Energie: Die Quelle Ihrer Lebenskraft',
    article2Content: 'Mitochondrien sind die Kraftwerke unserer Zellen und produzieren Energie in Form von ATP. Jede Zelle enthält Hunderte bis Tausende von Mitochondrien, und ihre Effizienz beeinflusst direkt unser Energieniveau.',
    article3Title: 'Von Nahrungsergänzungsmitteln zur Ernährung der 8. Generation',
    article3Content: 'Die Geschichte der Ernährungsansätze umfasst mehrere Generationen: von einfachen Vitaminen der ersten Generation bis zu revolutionären Zelltechnologien der achten Generation.',
    article4Title: 'Klinische Forschung: Bewiesene Wirksamkeit',
    article4Content: 'Ergebnisse unabhängiger klinischer Studien, die in führenden wissenschaftlichen Zentren weltweit durchgeführt wurden, bestätigen überzeugend die Wirksamkeit der Zellernährung der 8. Generation.',
    article5Title: 'Erholung von Stress auf Zellebene',
    article5Content: 'Moderner Stress hat eine zerstörerische Wirkung auf unsere Zellen und verursacht oxidativen Stress, Entzündungen und mitochondriale Dysfunktion.',
    article6Title: 'Biohacking und Zellernährung: Technologie-Synergie',
    article6Content: 'Biohacking ist die Anwendung wissenschaftlicher Erkenntnisse und Technologie zur Optimierung der Körperfunktion.',
  },
  zh: {
    home: '首页',
    articles: '文章',
    about: '关于我们',
    brandName: 'Success Together',
    navigation: '导航',
    contacts: '联系方式',
    email: '邮箱',
    copyright: '© 2025 Success Together. 保留所有权利。',
    footerDescription: '革命性的细胞营养，促进您的健康和活力。',
    articlesTitle: '文章',
    articlesSubtitle: '深入探索第8代细胞营养的世界',
    science: '科学',
    health: '健康',
    education: '教育',
    biohacking: '生物黑客',
    readTime: '分钟',
    article1Title: '细胞营养如何改变健康方法',
    article1Content: '第8代营养的发现开启了在分子水平上理解我们身体运作方式的新时代。细胞营养不仅仅是吃食物，而是将必要的营养素直接输送到身体细胞。',
    article2Title: '线粒体能量：您生命力的源泉',
    article2Content: '线粒体是我们细胞的发电厂，以ATP形式产生能量。每个细胞包含数百到数千个线粒体，它们的效率直接影响我们的能量水平。',
    article3Title: '从补充剂到第8代营养',
    article3Content: '营养方法的历史跨越了几代：从简单的第一代维生素到革命性的第八代细胞技术。',
    article4Title: '临床研究：经证实的有效性',
    article4Content: '在世界领先的科学中心进行的独立临床研究结果令人信服地证实了第8代细胞营养的有效性。',
    article5Title: '细胞层面的压力恢复',
    article5Content: '现代压力对我们的细胞产生破坏性影响，导致氧化应激、炎症和线粒体功能障碍。',
    article6Title: '生物黑客与细胞营养：技术协同',
    article6Content: '生物黑客是应用科学知识和技术来优化身体功能。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ru']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
